image_width: 1440
image_height: 1080
camera_name: hkcam
camera_matrix:
  rows: 3
  cols: 3
  data: [2397.681623,    0.     ,  741.552864 ,
            0.     , 2395.975018,  587.922606,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.044216 ,0.231471 ,0.002126 ,-0.000664 ,0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2388.15161,    0.     ,  748.55789,    0.     ,
            0.     , 2385.62866,  588.14207,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
