image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1785.04399,    0.     ,  730.96763,
            0.     , 1783.9721 ,  590.98998,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.055631, 0.080850, 0.001104, 0.000018, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1771.42639,    0.     ,  730.58134,    0.     ,
            0.     , 1773.89355,  591.37104,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]