image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1791.55218,    0.     ,  693.16282,
            0.     , 1789.89206,  563.40494,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.219706, 0.190480, -0.000629, -0.000486, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1732.33276,    0.     ,  690.65211,    0.     ,
            0.     , 1753.9408 ,  563.40914,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]