image_width: 1440
image_height: 1080
camera_name: hkcam
camera_matrix:
  rows: 3
  cols: 3
  data: [2395.72039,    0.     ,  748.2433 ,
            0.     , 2391.89136,  588.03087,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.033270, 0.066633, 0.001414, 0.001089, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2388.15161,    0.     ,  748.55789,    0.     ,
            0.     , 2385.62866,  588.14207,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
